version: '3'

services:
  postgres:
    image: debezium/postgres:12
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "prud1234"
      POSTGRES_USER: "local_user"
      POSTGRES_DB: "localdb"
    ports:
      - "5432:5432"
    networks:
      - development-network
      
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@dev.com"
      PGADMIN_DEFAULT_PASSWORD: "senha1234"
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - development-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - development-network

  broker:
    image: confluentinc/cp-server:5.5.1
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
    networks:
      - development-network

  connect:
    image: debezium/connect 
    hostname: connect
    container_name: connect
    ports:
      - "9093:9093"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my-connect-configs
      OFFSET_STORAGE_TOPIC: my-connect-offsets
      ADVERTISED_HOST_NAME: connect
      BOOTSTRAP_SERVERS: broker:29092
    depends_on:
      - zookeeper
      - broker
    networks:
      - development-network

networks: 
  development-network:
    driver: bridge
