version: '3'

services:
  postgres:
    image: timescale/timescaledb:latest-pg12
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
    networks:
      - development-network
      
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@dev.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - development-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - development-network

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - development-network

networks: 
  development-network:
    driver: bridge

volumes:
    postgres_database:
        external: true