version: '3'

services:
  postgres:
    image: debezium/example-postgres:1.3
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    networks:
      - development-network
      
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fernando.alves@prudential.com"
      PGADMIN_DEFAULT_PASSWORD: "prud1234"
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - development-network
  
  zookeeper:
    image: debezium/zookeeper:1.3
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - development-network

  broker:
    image: debezium/kafka:1.3
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - development-network

  connect:
    image: debezium/connect 
    hostname: connect
    container_name: connect
    ports:
      - "9093:8083"
    links:
      - broker
      - postgres
    environment:
      BOOTSTRAP_SERVERS: broker:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    depends_on:
      - broker
    networks:
      - development-network

networks: 
  development-network:
    driver: bridge